export const cityDictionary = {
  // 台灣城市
  台北: "Taipei",
  新北: "New Taipei",
  基隆: "Keelung",
  桃園: "Taoyuan",
  新竹: "Hsinchu",
  苗栗: "Miaoli",
  台中: "Taichung",
  台南: "Tainan City",
  高雄: "Kaohsiung City",
  屏東: "Pingtung",
  宜蘭: "Yilan",
  花蓮: "Hualien",
  台東: "Taitung",
  澎湖: "Penghu",
  金門: "Kinmen",
  馬祖: "Matsu",
  南投: "Nantou",
  彰化: "Changhua",
  雲林: "Yunlin",
  台中市: "Taichung",
  台南市: "Tainan",
  高雄市: "Kaohsiung",
  新竹市: "Hsinchu City",
  基隆市: "Keelung City",
  嘉義市: "Chiayi City",
  桃園市: "Taoyuan City",
  台北市: "Taipei City",
  新北市: "New Taipei City",
  宜蘭縣: "Yilan County",
  花蓮縣: "Hualien County",
  台東縣: "Taitung County",
  澎湖縣: "Penghu County",
  金門縣: "Kinmen County",
  馬祖列島: "Matsu Islands",
  南投縣: "Nantou County",
  彰化縣: "Changhua County",
  雲林縣: "Yunlin County",

  // 日本主要城市
  東京: "Tokyo",
  大阪: "Osaka",
  京都: "Kyoto",
  札幌: "Sapporo",
  名古屋: "Nagoya",
  橫濱: "Yokohama",
  福岡: "Fukuoka",
  仙台: "Sendai",
  廣島: "Hiroshima",
  神戶: "Kobe",
  那霸: "Naha",
  熊本: "Kumamoto",
  岡山: "Okayama",
  長崎: "Nagasaki",
  大分: "Oita",
  佐賀: "Saga",
  高松: "Takamatsu",
  松山: "Matsuyama",
  沖繩: "Okinawa",
  上越: "Joetsu",
  埼玉: "Saitama",
  千葉: "Chiba",
  茨城: "Ibaraki",
  栃木: "Tochigi",
  群馬: "Gunma",
  青森: "Aomori",
  岩手: "Iwate",
  宮城: "Miyagi",
  秋田: "Akita",
  山形: "Yamagata",
  福島: "Fukushima",
  新潟: "Niigata",
  富山: "Toyama",
  石川: "Ishikawa",
  福井: "Fukui",
  山梨: "Yamanashi",
  長野: "Nagano",
  岐阜: "Gifu",
  靜岡: "Shizuoka",
  愛知: "Aichi",
  三重: "Mie",
  滋賀: "Shiga",
  奈良: "Nara",
  和歌山: "Wakayama",
  鳥取: "Tottori",
  島根: "Shimane",
  岡山: "Okayama",
  廣島: "Hiroshima",
  山口: "Yamaguchi",
  德島: "Tokushima",
  香川: "Kagawa",
  愛媛: "Ehime",
  高知: "Kochi",
  福岡: "Fukuoka",
  佐賀: "Saga",
  長崎: "Nagasaki",
  熊本: "Kumamoto",
  大分: "Oita",
  宮崎: "Miyazaki",
  鹿兒島: "Kagoshima",
  沖繩: "Okinawa",
  大阪市: "Osaka",
  東京市: "Tokyo",
  京都市: "Kyoto",
  札幌市: "Sapporo",
  名古屋市: "Nagoya",
  福岡市: "Fukuoka",
  仙台市: "Sendai",
  廣島市: "Hiroshima",
  神戶市: "Kobe",
  熊本市: "Kumamoto",
  岡山市: "Okayama",
  長崎市: "Nagasaki",
  大分市: "Oita",
  佐賀市: "Saga",
  高松市: "Takamatsu",
  松山市: "Matsuyama",
  沖繩市: "Okinawa",
  埼玉市: "Saitama City",
  千葉市: "Chiba City",
  茨城縣: "Ibaraki Prefecture",
  栃木縣: "Tochigi Prefecture",
  群馬縣: "Gunma Prefecture",
  青森市: "Aomori City",
  岩手縣: "Iwate Prefecture",
  宮城縣: "Miyagi Prefecture",
  秋田市: "Akita City",
  山形市: "Yamagata City",
  福島市: "Fukushima City",
  新潟市: "Niigata City",
  富山市: "Toyama City",
  石川縣: "Ishikawa Prefecture",
  福井市: "Fukui City",
  山梨市: "Yamanashi City",
  長野市: "Nagano City",
  岐阜市: "Gifu City",
  靜岡市: "Shizuoka City",
  愛知市: "Aichi City",
  三重縣: "Mie Prefecture",
  滋賀市: "Shiga City",
  奈良市: "Nara City",
  和歌山市: "Wakayama City",
  鳥取市: "Tottori City",
  島根市: "Shimane City",
  岡山市: "Okayama City",
  廣島市: "Hiroshima City",
  山口市: "Yamaguchi City",
  德島市: "Tokushima City",
  香川市: "Kagawa City",
  愛媛市: "Ehime City",
  高知市: "Kochi City",
  福岡市: "Fukuoka City",
  佐賀市: "Saga City",
  長崎市: "Nagasaki City",
  熊本市: "Kumamoto City",
  大分市: "Oita City",
  宮崎市: "Miyazaki City",
  鹿兒島市: "Kagoshima City",
  沖繩市: "Okinawa City",

  // 美國主要城市
  紐約: "New York",
  洛杉磯: "Los Angeles",
  芝加哥: "Chicago",
  休斯頓: "Houston",
  鳳凰城: "Phoenix",
  費城: "Philadelphia",
  聖安東尼奧: "San Antonio",
  聖地牙哥: "San Diego",
  達拉斯: "Dallas",
  奧斯丁: "Austin",

  // 英國主要城市
  倫敦: "London",
  曼徹斯特: "Manchester",
  伯明翰: "Birmingham",
  利物浦: "Liverpool",
  格拉斯哥: "Glasgow",
  愛丁堡: "Edinburgh",
  布里斯托: "Bristol",

  // 法國主要城市
  巴黎: "Paris",
  馬賽: "Marseille",
  里昂: "Lyon",
  圖盧茲: "Toulouse",
  尼斯: "Nice",
  波爾多: "Bordeaux",

  // 德國主要城市
  柏林: "Berlin",
  漢堡: "Hamburg",
  慕尼黑: "Munich",
  科隆: "Cologne",
  法蘭克福: "Frankfurt",
  斯圖加特: "Stuttgart",

  // 加拿大主要城市
  多倫多: "Toronto",
  溫哥華: "Vancouver",
  蒙特利爾: "Montreal",
  卡爾加里: "Calgary",
  渥太華: "Ottawa",

  // 澳洲主要城市
  悉尼: "Sydney",
  墨爾本: "Melbourne",
  布里斯班: "Brisbane",
  珀斯: "Perth",
  阿德萊德: "Adelaide",

  // 德語區其他城市
  蘇黎世: "Zurich",
  日內瓦: "Geneva",
  維也納: "Vienna",
  蘭茨胡特: "Landschut",
  巴伐利亞: "Bavaria",

  // 南美洲城市
  聖保羅: "Sao Paulo",
  里約熱內盧: "Rio de Janeiro",
  布宜諾斯艾利斯: "Buenos Aires",
  聖地亞哥: "Santiago",

  // 中東城市
  迪拜: "Dubai",
  阿布扎比: "Abu Dhabi",
  伊斯坦布爾: "Istanbul",
  開羅: "Cairo",
  卡塔爾: "Doha",

  // 亞洲其他城市
  孟買: "Mumbai",
  新加坡: "Singapore",
  首爾: "Seoul",
  吉隆坡: "Kuala Lumpur",
  班加羅爾: "Bangalore",
  德里: "Delhi",

  // 非洲主要城市
  開羅: "Cairo",
  拉各斯: "Lagos",
  奈及利亞: "Abuja",
  約翰內斯堡: "Johannesburg",
  開普敦: "Cape Town",
};
