name: Deploy Weather App

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace API key
        run: |
          sed -i "s/OPENWEATHER_API_KEY: \`.*\`/OPENWEATHER_API_KEY: \`${{ secrets.OPENWEATHER_API_KEY }}\`/g" js/config.js
          echo "Updated config.js:"
          cat js/config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
